// Generated by ts-to-zod
import { z } from "zod";

export const rawGeneratorPluginConfigurationSchema = z.object({
    prepend: z.string().optional(),
    output: z.string().optional(),
    append: z.string().optional(),
});
