name: Build & Release

on: workflow_dispatch

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::$(echo jq -Mr '.version' < package.json)
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
