name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: Choose tag
        options:
          - alpha
          - latest

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get the version
        id: get_version
        run: echo "version=$(jq -Mr '.version' < lerna.json)" >> $GITHUB_OUTPUT
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      # Ensure npm 11.5.1 or later is installed for OIDC to work.
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install
        run: npm ci
      - name: Test
        run: npx nx run-many -t test
      - name: Test Build
        run: npx nx run-many -t build --parallel=1
      - name: Publish
        run:
          npx nx run-many -t publish --registry=npm --ver=${{steps.get_version.outputs.version}}
          --tag=${{github.event.inputs.tag}}
